services:
  nginx:
    image: nginx:alpine
    container_name: nginx_mudin
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_mudin
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/app
      - ./vendor:/var/www/app/vendor
      - ./public:/var/www/app/public

  db:
    image: mysql:latest
    container_name: db_mudin
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./mysql:/var/lib/mysql